id = "artisan-theme"
name = "Artisan Theme"
version = "0.0.1"
schema_version = 1
authors = ["VheissuLabs"]
description = "A clean light color theme inspired by Laravel's branding."
repository = "https://github.com/VheissuLabs/artisan-theme"
